### ISSUE TITLE
tests::fdpassing::test_fd_passing fails on Fedora

### ISSUE THREAD

**Issue by davide125** [KillingSpark/rustbus#72]
On a Fedora 34 box, when running `cargo test` I get a failure on this with:
```
thread 'tests::fdpassing::test_fd_passing' panicked at 'called `Result::unwrap()` on an `Err` value: UnmarshalError(Validation(InvalidSignature(EmptySignature)))', rustbus/src/tests/fdpassing.rs:37:70
```
This box is running `dbus-1.12.20` and `dbus-broker-29`.

Also, when running the test in a container without dbus running, I get
```
thread 'tests::fdpassing::test_fd_passing' panicked at 'called `Result::unwrap()` on an `Err` value: PathDoesNotExist("/run/dbus/system_bus_socket")', src/tests/fdpassing.rs:12:83
```

In the latter scenario, it might make sense to just skip the test as it's never going to succeed.

**Comment by KillingSpark** [comment]
Huh this is concerning, because the test runs fine on at least arch and ubuntu. And the marshalling code should not depend on the distro. Could you dig into this a bit? I currently do not have a fedora box at hand. A few println!s in the connection code should reveal why the heck an empty signature is received there.

Is it really ok to disable those checks if dbus is not present? This might result in silently not running important tests (fd passing is kind of essential).

**Comment by davide125** [comment]
Ok it looks like this failure only happen when running [dbus-broker](https://github.com/bus1/dbus-broker) as the system dbus message broker. I was able to verify this on a CentOS Stream 8 host, which ships with dbus-daemon by default, but also has packages for dbus-broker available. The test passes when running dbus-daemon, and it fails after switching to dbus-broker.

**Comment by davide125** [comment]
Output with some debugging println!s:
```
---- tests::fdpassing::test_fd_passing stdout ----
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [], raw_fds: [], sig: SignatureBuffer(""), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("Hello"), object: Some("/org/freedesktop/DBus"), destination: Some("org.freedesktop.DBus"), serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Call, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [], raw_fds: [], sig: SignatureBuffer(""), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("Hello"), object: Some("/org/freedesktop/DBus"), destination: Some("org.freedesktop.DBus"), serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Call, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [], raw_fds: [], sig: SignatureBuffer(""), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("Hello"), object: Some("/org/freedesktop/DBus"), destination: Some("org.freedesktop.DBus"), serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Call, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [], raw_fds: [], sig: SignatureBuffer(""), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("Hello"), object: Some("/org/freedesktop/DBus"), destination: Some("org.freedesktop.DBus"), serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Call, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [13, 0, 0, 0, 116, 121, 112, 101, 61, 39, 115, 105, 103, 110, 97, 108, 39, 0], raw_fds: [], sig: SignatureBuffer("s"), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("AddMatch"), object: Some("/org/freedesktop/DBus"), destination: Some("org.freedesktop.DBus"), serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Call, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [0, 0, 0, 0], raw_fds: [UnixFd(UnixFdInner { inner: 15 })], sig: SignatureBuffer("h"), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("io.killing.spark"), member: Some("TestSignal"), object: Some("/io/killing/spark"), destination: None, serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: Some(1) }, typ: Signal, flags: 0 }
send_message MarshalledMessage { body: MarshalledMessageBody { buf: [], raw_fds: [], sig: SignatureBuffer(""), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("io.killing.spark"), member: Some("TestSignal"), object: Some("/io/killing/spark"), destination: None, serial: None, sender: None, signature: None, error_name: None, response_serial: None, num_fds: None }, typ: Signal, flags: 0 }
wait_signal MarshalledMessage { body: MarshalledMessageBody { buf: [7, 0, 0, 0, 58, 49, 46, 51, 49, 49, 57, 0], raw_fds: [], sig: SignatureBuffer("s"), byteorder: LittleEndian }, dynheader: DynamicHeader { interface: Some("org.freedesktop.DBus"), member: Some("NameAcquired"), object: Some("/org/freedesktop/DBus"), destination: Some(":1.3119"), serial: Some(4294967295), sender: Some("org.freedesktop.DBus"), signature: Some("s"), error_name: None, response_serial: None, num_fds: None }, typ: Signal, flags: 1 }
thread 'tests::fdpassing::test_fd_passing' panicked at 'called `Result::unwrap()` on an `Err` value: UnmarshalError(Validation(InvalidSignature(EmptySignature)))', rustbus/src/tests/fdpassing.rs:37:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running `busctl monitor` concurrently, these are the only messages I see fly by that seem related:
```
‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=1  Timestamp="Tue 2021-07-06 21:46:22.332601 UTC"
  Sender=:1.3118  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.3118
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=-1  ReplyCookie=1  Timestamp="Tue 2021-07-06 21:46:22.332628 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3118
  MESSAGE "s" {
          STRING ":1.3118";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:22.332639 UTC"
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.3118";
          STRING "";
          STRING ":1.3118";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:22.332647 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3118  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.3118";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=1  Timestamp="Tue 2021-07-06 21:46:22.332878 UTC"
  Sender=:1.3119  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.3119
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=-1  ReplyCookie=1  Timestamp="Tue 2021-07-06 21:46:22.332898 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3119
  MESSAGE "s" {
          STRING ":1.3119";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:22.332920 UTC"
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.3119";
          STRING "";
          STRING ":1.3119";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:22.332935 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3119  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.3119";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2  Timestamp="Tue 2021-07-06 21:46:22.333053 UTC"
  Sender=:1.3118  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.3118
  MESSAGE "" {
  };

‣ Type=error  Endian=l  Flags=1  Version=1 Cookie=-1  ReplyCookie=2  Timestamp="Tue 2021-07-06 21:46:22.333082 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3118
  ErrorName=org.freedesktop.DBus.Error.Failed  ErrorMessage="Hello() already called"
  MESSAGE "s" {
          STRING "Hello() already called";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2  Timestamp="Tue 2021-07-06 21:46:22.333092 UTC"
  Sender=:1.3119  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.3119
  MESSAGE "" {
  };

‣ Type=error  Endian=l  Flags=1  Version=1 Cookie=-1  ReplyCookie=2  Timestamp="Tue 2021-07-06 21:46:22.333098 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3119
  ErrorName=org.freedesktop.DBus.Error.Failed  ErrorMessage="Hello() already called"
  MESSAGE "s" {
          STRING "Hello() already called";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=3  Timestamp="Tue 2021-07-06 21:46:22.333129 UTC"
  Sender=:1.3119  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=AddMatch
  UniqueName=:1.3119
  MESSAGE "s" {
          STRING "type='signal'";
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=-1  ReplyCookie=3  Timestamp="Tue 2021-07-06 21:46:22.333143 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3119
  MESSAGE "" {
  };

‣ Type=signal  Endian=l  Flags=0  Version=1 Cookie=3  Timestamp="Tue 2021-07-06 21:46:23.334488 UTC"
  Sender=:1.3118  Path=/io/killing/spark  Interface=io.killing.spark  Member=TestSignal
  UniqueName=:1.3118
  MESSAGE "h" {
          UNIX_FD 4;
  };

‣ Type=signal  Endian=l  Flags=0  Version=1 Cookie=4  Timestamp="Tue 2021-07-06 21:46:23.334572 UTC"
  Sender=:1.3118  Path=/io/killing/spark  Interface=io.killing.spark  Member=TestSignal
  UniqueName=:1.3118
  MESSAGE "" {
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:23.334832 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3119  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.3119";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:23.334907 UTC"
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.3119";
          STRING ":1.3119";
          STRING "";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:23.334961 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.3118  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.3118";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=-1  Timestamp="Tue 2021-07-06 21:46:23.335034 UTC"
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.3118";
          STRING ":1.3118";
          STRING "";
  };
```

**Comment by KillingSpark** [comment]
I'll investigate this myself, I can install dbus broker on my arch box. One funny thing I just witnessed: discord crashes if the dbus-daemon is stopped and will not start with dbus-broker running. I'll see what I can find over the weekend.

**Comment by davide125** [comment]
FYI switching between dbus-daemon and dbus-broker requires a reboot. See their wiki for more details: https://github.com/bus1/dbus-broker/wiki#using-dbus-broker

**Comment by KillingSpark** [comment]
I found the issue. dbus-broker explicitly sends an empty signature header field if the message does not contain any content. Omitting this header field means the same thing and dbus-daemon seems to omit it, which is why this hasn't been found yet.

**Comment by davide125** [comment]
Thanks! I can confirm the test is now passing on master when run on Fedora 34.

**Comment by davide125** [comment]
Working fine in 0.16.0 so I think we can close this. Thanks again for your help!

**Comment by KillingSpark** [comment]
No problem!
